In [1]:
import pandas as pd

In [2]:
"""
Ye dictionary di hui hai:
data = {
    "Name": ["Amit", "Priya", "Rahul"],
    "Age": [25, 28, 30],
    "Salary": [50000, 60000, 70000]
}
"""
data = {
    "Name": ["Amit", "Priya", "Rahul"],
    "Age": [25, 28, 30],
    "Salary": [50000, 60000, 70000]
}

In [3]:
df = pd.DataFrame(data)

In [4]:
df

    Name  Age  Salary
0   Amit   25   50000
1  Priya   28   60000
2  Rahul   30   70000

In [14]:
"""2. Display Information
Upar wale DataFrame ke liye:
First 2 rows
Last row
Column names
Shape
nikalo."""

'2. Display Information\nUpar wale DataFrame ke liye:\nFirst 2 rows\nLast row\nColumn names\nShape\nnikalo.'

In [5]:
df.head(2)

    Name  Age  Salary
0   Amit   25   50000
1  Priya   28   60000

In [7]:

df.tail(1)

    Name  Age  Salary
2  Rahul   30   70000

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      object
 1   Age     3 non-null      int64
 2   Salary  3 non-null      int64
dtypes: int64(2), object(1)
memory usage: 200.0+ bytes

In [11]:
df.columns

Index(['Name', 'Age', 'Salary'], dtype='object')

In [12]:
df.shape

(3, 3)

In [13]:
"""3. Select Columns
Print:
Name
Salary
columns."""

'3. Select Columns\nPrint:\nName\nSalary\ncolumns.'

In [15]:
df["Name"]

0     Amit
1    Priya
2    Rahul
Name: Name, dtype: object

In [16]:
df["Salary"]

0    50000
1    60000
2    70000
Name: Salary, dtype: int64

In [17]:
""" 
4. Select Single Row
Rahul wali row nikalo using:
loc
iloc
"""

' \n4. Select Single Row\nRahul wali row nikalo using:\nloc\niloc\n'

In [20]:
print(df.loc[0])

Name       Amit
Age          25
Salary    50000
Name: 0, dtype: object

In [23]:
data = df[df["Name"] == "Rahul"].index[0]

In [25]:
df.loc[data]

Name      Rahul
Age          30
Salary    70000
Name: 2, dtype: object

In [26]:
df.iloc[data]

Name      Rahul
Age          30
Salary    70000
Name: 2, dtype: object

In [27]:
""" 
5. Add New Column
Ek new column banao:
Bonus = Salary * 0.10
"""

' \n5. Add New Column\nEk new column banao:\nBonus = Salary * 0.10\n'

In [28]:
df

    Name  Age  Salary
0   Amit   25   50000
1  Priya   28   60000
2  Rahul   30   70000

In [29]:
df["Bonas"] = df["Salary"] * 0.10

In [30]:
df

    Name  Age  Salary   Bonas
0   Amit   25   50000  5000.0
1  Priya   28   60000  6000.0
2  Rahul   30   70000  7000.0

In [31]:
""" 
6. Rename Column
Salary
ko
Monthly_Salary
rename karo.
"""

' \n6. Rename Column\nSalary\nko\nMonthly_Salary\nrename karo.\n'

In [33]:
df.rename(columns={"Salary": "Monthly_Salary"}, inplace=True)

In [34]:
df

    Name  Age  Monthly_Salary   Bonas
0   Amit   25           50000  5000.0
1  Priya   28           60000  6000.0
2  Rahul   30           70000  7000.0

In [35]:
""" 
7. Delete Column
Bonus column hatao.
"""

' \n7. Delete Column\nBonus column hatao.\n'

In [37]:
del df["Bonas"]

In [38]:
df

    Name  Age  Monthly_Salary
0   Amit   25           50000
1  Priya   28           60000
2  Rahul   30           70000

In [39]:
# df.drop(
#         columns=["Bonas"],
#         inplace=True
# )

In [40]:
""" 
8. Salary Greater Than 60000
Sirf un employees ko dikhao jinki salary 60000 se zyada hai.
"""

' \n8. Salary Greater Than 60000\nSirf un employees ko dikhao jinki salary 60000 se zyada hai.\n'

In [41]:
df

    Name  Age  Monthly_Salary
0   Amit   25           50000
1  Priya   28           60000
2  Rahul   30           70000

In [42]:
df[df["Monthly_Salary"] > 60000]

    Name  Age  Monthly_Salary
2  Rahul   30           70000

In [47]:
df[(df["Monthly_Salary"] > 60000) & (df["Age"] > 25)]

    Name  Age  Monthly_Salary
2  Rahul   30           70000

In [48]:
""" 
10. String Filtering
Sirf un logon ko dikhao jinke naam me letter:
"a"

aata ho.
"""

' \n10. String Filtering\nSirf un logon ko dikhao jinke naam me letter:\n"a"\n\naata ho.\n'