In [1]:
print("hello")

hello

In [2]:
import pandas as pd

In [5]:
data = pd.read_excel("ESD.xlsx")

In [8]:
# print(data)

data.loc[(data['Bonus %'] == 0), "Gets Bonas"] = "No Bonas"
data.loc[(data["Bonus %"] > 0), "Gets Bonas"] = "Bonas"

In [9]:
data.head(15)

,EEID,Full Name,Job Title,Department,Business Unit,Gender,Ethnicity,Age,Hire Date,Annual Salary,Bonus %,Country,City,Exit Date,Gets Bonas
0,E02387,Emily Davis,Sr. Manger,IT,Research & Development,Female,Black,55,2016-04-08,141604,0.15,United States,Seattle,2021-10-16,Bonas
1,E04105,Theodore Dinh,Technical Architect,IT,Manufacturing,Male,Asian,59,1997-11-29,99975,0.00,China,Chongqing,NaT,No Bonas
2,E02572,Luna Sanders,Director,Finance,Speciality Products,Female,Caucasian,50,2006-10-26,163099,0.20,United States,Chicago,NaT,Bonas
3,E02832,Penelope Jordan,Computer Systems Manager,IT,Manufacturing,Female,Caucasian,26,2019-09-27,84913,0.07,United States,Chicago,NaT,Bonas
4,E01639,Austin Vo,Sr. Analyst,Finance,Manufacturing,Male,Asian,55,1995-11-20,95409,0.00,United States,Phoenix,NaT,No Bonas
5,E00644,Joshua Gupta,Account Representative,Sales,Corporate,Male,Asian,57,2017-01-24,50994,0.00,China,Chongqing,NaT,No Bonas
6,E01550,Ruby Barnes,Manager,IT,Corporate,Female,Caucasian,27,2020-07-01,119746,0.10,United States,Phoenix,NaT,Bonas
7,E04332,Luke Martin,Analyst,Finance,Manufacturing,Male,Black,25,2020-05-16,41336,0.00,United States,Miami,2021-05-20,No Bonas
8,E04533,Easton Bailey,Manager,Accounting,Manufacturing,Male,Caucasian,29,2019-01-25,113527,0.06,United States,Austin,NaT,Bonas
9,E03838,Madeline Walker,Sr. Analyst,Finance,Speciality Products,Female,Caucasian,34,2018-06-13,77203,0.00,United States,Chicago,NaT,No Bonas
10,E00591,Savannah Ali,Sr. Manger,Human Resources,Manufacturing,Female,Asian,36,2009-02-11,157333,0.15,United States,Miami,NaT,Bonas
11,E03344,Camila Rogers,Controls Engineer,Engineering,Speciality Products,Female,Caucasian,27,2021-10-21,109851,0.00,United States,Seattle,NaT,No Bonas
12,E00530,Eli Jones,Manager,Human Resources,Manufacturing,Male,Caucasian,59,1999-03-14,105086,0.09,United States,Austin,NaT,Bonas
13,E04239,Everleigh Ng,Sr. Manger,Finance,Research & Development,Female,Asian,51,2021-06-10,146742,0.10,China,Shanghai,NaT,Bonas
14,E03496,Robert Yang,Sr. Analyst,Accounting,Speciality Products,Male,Asian,31,2017-11-04,97078,0.00,United States,Austin,2020-03-09,No Bonas

create full name column

In [16]:
data = pd.read_excel("practiceset.xlsx")

In [17]:
data

  First Name Last Name  Salary   EEID
0      Aarav    Sharma   68450  EE001
1      Priya     Mehta   75200  EE002
2      Rohan     Verma   59800  EE003
3     Ananya      Iyer   82100  EE004
4     Vikram     Patel   70950  EE005
5      Sneha     Reddy   63500  EE006
6      Karan    Kapoor   91300  EE007
7       Neha      Nair   66750  EE008
8      Arjun     Singh   78400  EE009
9     Ishita     Joshi   72600  EE010

In [18]:
# data.loc[(data['Bonus %'] == 0), "Gets Bonas"] = "No Bonas"
# data.loc[(data["Bonus %"] > 0), "Gets Bonas"] = "Bonas"

In [21]:
data["Full Name"] = data["First Name"] + " " + data["Last Name"]

In [22]:
data

  First Name Last Name  Salary   EEID     Full Name
0      Aarav    Sharma   68450  EE001  Aarav Sharma
1      Priya     Mehta   75200  EE002   Priya Mehta
2      Rohan     Verma   59800  EE003   Rohan Verma
3     Ananya      Iyer   82100  EE004   Ananya Iyer
4     Vikram     Patel   70950  EE005  Vikram Patel
5      Sneha     Reddy   63500  EE006   Sneha Reddy
6      Karan    Kapoor   91300  EE007  Karan Kapoor
7       Neha      Nair   66750  EE008     Neha Nair
8      Arjun     Singh   78400  EE009   Arjun Singh
9     Ishita     Joshi   72600  EE010  Ishita Joshi

20% of salary Column as bonas

In [23]:
data

  First Name Last Name  Salary   EEID     Full Name
0      Aarav    Sharma   68450  EE001  Aarav Sharma
1      Priya     Mehta   75200  EE002   Priya Mehta
2      Rohan     Verma   59800  EE003   Rohan Verma
3     Ananya      Iyer   82100  EE004   Ananya Iyer
4     Vikram     Patel   70950  EE005  Vikram Patel
5      Sneha     Reddy   63500  EE006   Sneha Reddy
6      Karan    Kapoor   91300  EE007  Karan Kapoor
7       Neha      Nair   66750  EE008     Neha Nair
8      Arjun     Singh   78400  EE009   Arjun Singh
9     Ishita     Joshi   72600  EE010  Ishita Joshi

In [24]:
data["Bonas"] = (data["Salary"]/100)*20

In [25]:
data

  First Name Last Name  Salary   EEID     Full Name    Bonas
0      Aarav    Sharma   68450  EE001  Aarav Sharma  13690.0
1      Priya     Mehta   75200  EE002   Priya Mehta  15040.0
2      Rohan     Verma   59800  EE003   Rohan Verma  11960.0
3     Ananya      Iyer   82100  EE004   Ananya Iyer  16420.0
4     Vikram     Patel   70950  EE005  Vikram Patel  14190.0
5      Sneha     Reddy   63500  EE006   Sneha Reddy  12700.0
6      Karan    Kapoor   91300  EE007  Karan Kapoor  18260.0
7       Neha      Nair   66750  EE008     Neha Nair  13350.0
8      Arjun     Singh   78400  EE009   Arjun Singh  15680.0
9     Ishita     Joshi   72600  EE010  Ishita Joshi  14520.0

new Salary Column Bonas + salary

In [26]:
data["Total"] = data["Bonas"] + data["Salary"]

In [27]:
data

  First Name Last Name  Salary   EEID     Full Name    Bonas     Total
0      Aarav    Sharma   68450  EE001  Aarav Sharma  13690.0   82140.0
1      Priya     Mehta   75200  EE002   Priya Mehta  15040.0   90240.0
2      Rohan     Verma   59800  EE003   Rohan Verma  11960.0   71760.0
3     Ananya      Iyer   82100  EE004   Ananya Iyer  16420.0   98520.0
4     Vikram     Patel   70950  EE005  Vikram Patel  14190.0   85140.0
5      Sneha     Reddy   63500  EE006   Sneha Reddy  12700.0   76200.0
6      Karan    Kapoor   91300  EE007  Karan Kapoor  18260.0  109560.0
7       Neha      Nair   66750  EE008     Neha Nair  13350.0   80100.0
8      Arjun     Singh   78400  EE009   Arjun Singh  15680.0   94080.0
9     Ishita     Joshi   72600  EE010  Ishita Joshi  14520.0   87120.0

In [28]:
dictionary = {"Months":["January", "Fabruary", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"]}

data = pd.DataFrame(dictionary)
data

       Months
0     January
1    Fabruary
2       March
3       April
4         May
5        June
6        July
7      August
8   September
9     October
10   November
11   December

In [29]:
def extract(value):
    return value[0:3]

In [30]:
data["Sort"] = data["Months"].map(extract)

In [31]:
data

       Months Sort
0     January  Jan
1    Fabruary  Fab
2       March  Mar
3       April  Apr
4         May  May
5        June  Jun
6        July  Jul
7      August  Aug
8   September  Sep
9     October  Oct
10   November  Nov
11   December  Dec