In [2]:
import pandas as pd

In [3]:
data = {"Fruits":["Mango", "graps", "papaya", "banana", "Carrot"],
        "Price":[120,200,141,170,55],
        "quantity":[7,12,8,80,90]}

df1 = pd.DataFrame(data)

In [4]:
df1

   Fruits  Price  quantity
0   Mango    120         7
1   graps    200        12
2  papaya    141         8
3  banana    170        80
4  Carrot     55        90

In [5]:
df2 = pd.DataFrame(data)

df2.loc[0, "Price"] = 135
df2.loc[2, "Price"] = 145
df2.loc[3, "Price"] = 88
df2.loc[4, "Price"] = 72


df2.loc[0, "quantity"] = 15
df2.loc[2, "quantity"] = 14
df2.loc[3, "quantity"] = 81
df2.loc[4, "quantity"] = 45

In [6]:
df2

   Fruits  Price  quantity
0   Mango    135        15
1   graps    200        12
2  papaya    145        14
3  banana     88        81
4  Carrot     72        45

In [7]:
print(df1.equals(df2))

False

In [8]:
df1.shape == df2.shape

True

In [9]:
df1.compare(df2)

   Price        quantity
    self  other     self other
0  120.0  135.0      7.0  15.0
2  141.0  145.0      8.0  14.0
3  170.0   88.0     80.0  81.0
4   55.0   72.0     90.0  45.0

In [10]:
df1.compare(df2, keep_shape=True)

  Fruits        Price        quantity
    self other   self  other     self other
0    NaN   NaN  120.0  135.0      7.0  15.0
1    NaN   NaN    NaN    NaN      NaN   NaN
2    NaN   NaN  141.0  145.0      8.0  14.0
3    NaN   NaN  170.0   88.0     80.0  81.0
4    NaN   NaN   55.0   72.0     90.0  45.0

In [11]:
df1.compare(df2, keep_equal=True)

  Price       quantity
   self other     self other
0   120   135        7    15
2   141   145        8    14
3   170    88       80    81
4    55    72       90    45