In [6]:
# create dataframe using dictionary

import pandas as pd

data = {"Name": ["John", "Peater", "Jailly"],
        "Age": [22,19,34],
        "Salary": [65000,40000,45000]}

df = pd.DataFrame(data)
print(df)

     Name  Age  Salary
0    John   22   65000
1  Peater   19   40000
2  Jailly   34   45000

In [6]:
data = pd.read_excel("D:/Excel Learnig\Book1.xlsx")

In [7]:
data

,Full name,Email,Department,Join date,Leave balance,Sellary,Bonas %,Project Start,Project End,Weekend join
0,john Doe,john@example.com,Sales,2022-05-10,5,50000,0.10,2024-06-01,2024-06-15,NaN
1,jane smith,jane@example.com,Marketing,2023-01-15,12,60000,0.15,2024-06-02,2024-06-16,NaN
2,ALICE JOHNSON,alice@example.com,Sales,2021-07-01,0,55000,0.10,2024-06-03,2024-06-17,NaN
3,BOB Brown,bob@example.com,HR,2023-10-20,8,45000,0.05,2024-06-04,2024-06-18,NaN
4,Eva White,eva@example.com,MArketing,2020-03-05,2,70000,0.20,2024-06-05,2024-06-19,NaN

In [14]:
import pandas as pd

data = pd.read_csv(
    "student-data.csv",
    # engine="python"
)

data.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,internet,romantic,famrel,freetime,goout,Dalc,Walc,health,absences,passed
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,no,no,4,3,4,1,1,3,6,no
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,yes,no,5,3,3,1,1,3,4,no
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,yes,no,4,3,2,2,3,3,10,yes
3,GP,F,15,U,GT3,T,4,2,health,services,...,yes,yes,3,2,2,1,1,5,2,yes
4,GP,F,16,U,GT3,T,3,3,other,other,...,no,no,4,3,2,1,2,5,4,yes

In [15]:
print(data.head(10))

  school sex  age address famsize Pstatus  Medu  Fedu      Mjob      Fjob  \
0     GP   F   18       U     GT3       A     4     4   at_home   teacher
1     GP   F   17       U     GT3       T     1     1   at_home     other
2     GP   F   15       U     LE3       T     1     1   at_home     other
3     GP   F   15       U     GT3       T     4     2    health  services
4     GP   F   16       U     GT3       T     3     3     other     other
5     GP   M   16       U     LE3       T     4     3  services     other
6     GP   M   16       U     LE3       T     2     2     other     other
7     GP   F   17       U     GT3       A     4     4     other   teacher
8     GP   M   15       U     LE3       A     3     2  services     other
9     GP   M   15       U     GT3       T     3     4     other     other

   ... internet romantic  famrel  freetime  goout Dalc Walc health absences  \
0  ...       no       no       4         3      4    1    1      3        6
1  ...      yes       no       5         3      3    1    1      3        4
2  ...      yes       no       4         3      2    2    3      3       10
3  ...      yes      yes       3         2      2    1    1      5        2
4  ...       no       no       4         3      2    1    2      5        4
5  ...      yes       no       5         4      2    1    2      5       10
6  ...      yes       no       4         4      4    1    1      3        0
7  ...       no       no       4         1      4    1    1      1        6
8  ...      yes       no       4         2      2    1    1      1        0
9  ...      yes       no       5         5      1    1    1      5        0

  passed
0     no
1     no
2    yes
3    yes
4    yes
5    yes
6    yes
7     no
8    yes
9    yes

[10 rows x 31 columns]

In [16]:
data.tail(12)

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,internet,romantic,famrel,freetime,goout,Dalc,Walc,health,absences,passed
383,MS,M,19,R,GT3,T,1,1,other,services,...,no,no,4,3,2,1,3,5,0,no
384,MS,M,18,R,GT3,T,4,2,other,other,...,no,no,5,4,3,4,3,3,14,no
385,MS,F,18,R,GT3,T,2,2,at_home,other,...,no,no,5,3,3,1,3,4,2,yes
386,MS,F,18,R,GT3,T,4,4,teacher,at_home,...,yes,yes,4,4,3,2,2,5,7,no
387,MS,F,19,R,GT3,T,2,3,services,other,...,yes,no,5,4,2,1,2,5,0,no
388,MS,F,18,U,LE3,T,3,1,teacher,services,...,yes,no,4,3,4,1,1,1,0,no
389,MS,F,18,U,GT3,T,1,1,other,other,...,no,no,1,1,1,1,1,5,0,no
390,MS,M,20,U,LE3,A,2,2,services,services,...,no,no,5,5,4,4,5,4,11,no
391,MS,M,17,U,LE3,T,3,1,services,services,...,yes,no,2,4,5,3,4,2,3,yes
392,MS,M,21,R,GT3,T,1,1,other,other,...,no,no,5,5,3,3,3,3,3,no
393,MS,M,18,R,LE3,T,3,2,services,other,...,yes,no,4,4,1,3,4,5,0,yes
394,MS,M,19,U,LE3,T,1,1,other,at_home,...,yes,no,3,2,3,3,3,5,5,no

In [17]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 395 entries, 0 to 394
Data columns (total 31 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   school      395 non-null    object
 1   sex         395 non-null    object
 2   age         395 non-null    int64
 3   address     395 non-null    object
 4   famsize     395 non-null    object
 5   Pstatus     395 non-null    object
 6   Medu        395 non-null    int64
 7   Fedu        395 non-null    int64
 8   Mjob        395 non-null    object
 9   Fjob        395 non-null    object
 10  reason      395 non-null    object
 11  guardian    395 non-null    object
 12  traveltime  395 non-null    int64
 13  studytime   395 non-null    int64
 14  failures    395 non-null    int64
 15  schoolsup   395 non-null    object
 16  famsup      395 non-null    object
 17  paid        395 non-null    object
 18  activities  395 non-null    object
 19  nursery     395 non-null    object
 20  higher      395 non-null    object
 21  internet    395 non-null    object
 22  romantic    395 non-null    object
 23  famrel      395 non-null    int64
 24  freetime    395 non-null    int64
 25  goout       395 non-null    int64
 26  Dalc        395 non-null    int64
 27  Walc        395 non-null    int64
 28  health      395 non-null    int64
 29  absences    395 non-null    int64
 30  passed      395 non-null    object
dtypes: int64(13), object(18)
memory usage: 95.8+ KB

In [18]:
data.describe()

,age,Medu,Fedu,traveltime,studytime,failures,famrel,freetime,goout,Dalc,Walc,health,absences
count,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000
mean,16.696203,2.749367,2.521519,1.448101,2.035443,0.334177,3.944304,3.235443,3.108861,1.481013,2.291139,3.554430,5.708861
std,1.276043,1.094735,1.088201,0.697505,0.839240,0.743651,0.896659,0.998862,1.113278,0.890741,1.287897,1.390303,8.003096
min,15.000000,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000
25%,16.000000,2.000000,2.000000,1.000000,1.000000,0.000000,4.000000,3.000000,2.000000,1.000000,1.000000,3.000000,0.000000
50%,17.000000,3.000000,2.000000,1.000000,2.000000,0.000000,4.000000,3.000000,3.000000,1.000000,2.000000,4.000000,4.000000
75%,18.000000,4.000000,3.000000,2.000000,2.000000,0.000000,5.000000,4.000000,4.000000,2.000000,3.000000,5.000000,8.000000
max,22.000000,4.000000,4.000000,4.000000,4.000000,3.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,75.000000

In [19]:
data.isnull()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,internet,romantic,famrel,freetime,goout,Dalc,Walc,health,absences,passed
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
391,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
392,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
393,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
394,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [20]:
data.isnull().sum()

school        0
sex           0
age           0
address       0
famsize       0
Pstatus       0
Medu          0
Fedu          0
Mjob          0
Fjob          0
reason        0
guardian      0
traveltime    0
studytime     0
failures      0
schoolsup     0
famsup        0
paid          0
activities    0
nursery       0
higher        0
internet      0
romantic      0
famrel        0
freetime      0
goout         0
Dalc          0
Walc          0
health        0
absences      0
passed        0
dtype: int64