In [3]:
import pandas as pd
import numpy as np

In [4]:
data = pd.read_excel("groupByprob.xlsx")
data.head(5)

   Empid          name  gender  age  salary       city Department
0  E1001  Aarav Sharma    Male   24   42000     Mumbai         HR
1  E1002    Priya Nair  Female   29   58000  Bengaluru    Finance
2  E1003   Rohan Mehta    Male   31   64000      Delhi         IT
3  E1004    Sneha Iyer  Female   27   51000    Chennai      Sales
4  E1005  Vikram Singh    Male   35   72000       Pune  Marketing

In [5]:
# Department wise total salary nikalo.
grp = data.groupby(["Department"])["salary"].sum()

In [6]:
grp

Department
Admin         248500
Finance       296000
HR            300500
IT            300500
Marketing     280500
Operations    197500
Sales         290000
Support       244000
Name: salary, dtype: int64

In [7]:
# Department wise average salary nikalo.
grp = data.groupby(["Department"])["salary"].mean()

In [8]:
grp

Department
Admin         62125.0
Finance       59200.0
HR            60100.0
IT            60100.0
Marketing     70125.0
Operations    49375.0
Sales         58000.0
Support       61000.0
Name: salary, dtype: float64

In [10]:
data.head(5)

   Empid          name  gender  age  salary       city Department
0  E1001  Aarav Sharma    Male   24   42000     Mumbai         HR
1  E1002    Priya Nair  Female   29   58000  Bengaluru    Finance
2  E1003   Rohan Mehta    Male   31   64000      Delhi         IT
3  E1004    Sneha Iyer  Female   27   51000    Chennai      Sales
4  E1005  Vikram Singh    Male   35   72000       Pune  Marketing

In [14]:
# Department wise employee count nikalo.
grp = data.groupby(["Department"]).size()

In [15]:
grp

Department
Admin         4
Finance       5
HR            5
IT            5
Marketing     4
Operations    4
Sales         5
Support       4
dtype: int64

In [ ]:
# Department wise max salary nikalo.
grp = data.groupby(["Department"])["salary"].max()

# grp = data.groupby(["Department"]).agg({"salary":"max"})

In [17]:
grp

Department
Admin         76000
Finance       73500
HR            81000
IT            68500
Marketing     79000
Operations    54500
Sales         71000
Support       66000
Name: salary, dtype: int64

In [25]:
# Department wise max salary nikalo.
grp = data.groupby(["Department", "name"]).agg({"salary":"max"})

In [26]:
grp

                           salary
Department name
Admin      Kabir Ali        46000
           Karan Patel      69000
           Manish Gupta     76000
           Yash Thakur      57500
Finance    Anika Paul       51500
           Ishita Kapoor    45000
           Meera Pillai     68000
           Nandini Roy      73500
           Priya Nair       58000
HR         Aarav Sharma     42000
           Mohit Saxena     62500
           Nitin Arora      48000
           Rahul Joshi      67000
           Ritesh Yadav     81000
IT         Aditya Rao       61000
           Arjun Bose       52000
           Harsh Vora       55000
           Rohan Mehta      64000
           Varun Desai      68500
Marketing  Dev Malhotra     79000
           Saurabh Mishra   70500
           Siddharth Jain   59000
           Vikram Singh     72000
Operations Aisha Khan       43000
           Ananya Das       47000
           Kavya Reddy      53000
           Palak Bansal     54500
Sales      Bhavna Goel      58500
           Diya Chawla      49000
           Pooja Menon      71000
           Simran Kaur      60500
           Sneha Iyer       51000
Support    Neha Verma       56000
           Ritika Saha      62000
           Shruti Sen       60000
           Tanvi Kulkarni   66000

In [28]:
idx = data.groupby(["Department"])["salary"].idxmax()

In [29]:
idx

Department
Admin         14
Finance       25
HR            34
IT            32
Marketing     20
Operations    29
Sales         11
Support       23
Name: salary, dtype: int64

In [35]:
data.loc[idx,["Empid", "name", "Department", "salary"]]

    Empid            name  Department  salary
14  E1015    Manish Gupta       Admin   76000
25  E1026     Nandini Roy     Finance   73500
34  E1035    Ritesh Yadav          HR   81000
32  E1033     Varun Desai          IT   68500
20  E1021    Dev Malhotra   Marketing   79000
29  E1030    Palak Bansal  Operations   54500
11  E1012     Pooja Menon       Sales   71000
23  E1024  Tanvi Kulkarni     Support   66000

In [31]:
data.loc[data.groupby("Department")["salary"].idxmax()]

    Empid            name  gender  age  salary       city  Department
14  E1015    Manish Gupta    Male   36   76000      Noida       Admin
25  E1026     Nandini Roy  Female   35   73500     Ranchi     Finance
34  E1035    Ritesh Yadav    Male   38   81000     Meerut          HR
32  E1033     Varun Desai    Male   33   68500     Rajkot          IT
20  E1021    Dev Malhotra    Male   37   79000  Faridabad   Marketing
29  E1030    Palak Bansal  Female   28   54500   Ludhiana  Operations
11  E1012     Pooja Menon  Female   34   71000      Kochi       Sales
23  E1024  Tanvi Kulkarni  Female   32   66000     Nashik     Support

In [33]:
idx = data.groupby("Department")["salary"].idxmax()
result = data.loc[idx, ["Empid", "name", "Department", "salary"]]

print(result)

    Empid            name  Department  salary
14  E1015    Manish Gupta       Admin   76000
25  E1026     Nandini Roy     Finance   73500
34  E1035    Ritesh Yadav          HR   81000
32  E1033     Varun Desai          IT   68500
20  E1021    Dev Malhotra   Marketing   79000
29  E1030    Palak Bansal  Operations   54500
11  E1012     Pooja Menon       Sales   71000
23  E1024  Tanvi Kulkarni     Support   66000

In [36]:
# Department wise min salary nikalo.
grp = data.groupby(["Department"])["salary"].min()
grp

Department
Admin         46000
Finance       45000
HR            42000
IT            52000
Marketing     59000
Operations    43000
Sales         49000
Support       56000
Name: salary, dtype: int64

In [40]:
idx = data.groupby(["Department"])["salary"].idxmin()
prt = data.loc[idx, ["Empid", "name", "salary"]]

In [41]:
prt

    Empid            name  salary
30  E1031       Kabir Ali   46000
9   E1010   Ishita Kapoor   45000
0   E1001    Aarav Sharma   42000
24  E1025      Arjun Bose   52000
12  E1013  Siddharth Jain   59000
21  E1022      Aisha Khan   43000
27  E1028     Diya Chawla   49000
7   E1008      Neha Verma   56000

In [42]:
# Ek hi query me sum, mean, max nikalo.
grp = data.groupby(["Department"]).agg({"salary": ["min","max", "mean", "sum", "count"]})

In [43]:
grp

           salary
              min    max     mean     sum count
Department
Admin       46000  76000  62125.0  248500     4
Finance     45000  73500  59200.0  296000     5
HR          42000  81000  60100.0  300500     5
IT          52000  68500  60100.0  300500     5
Marketing   59000  79000  70125.0  280500     4
Operations  43000  54500  49375.0  197500     4
Sales       49000  71000  58000.0  290000     5
Support     56000  66000  61000.0  244000     4

In [44]:
grp = data.groupby(["Department", "gender"]).agg({"salary": ["min","max", "mean", "sum", "count"]})

In [45]:
grp

                  salary
                     min    max     mean     sum count
Department gender
Admin      Male    46000  76000  62125.0  248500     4
Finance    Female  45000  73500  59200.0  296000     5
HR         Male    42000  81000  60100.0  300500     5
IT         Male    52000  68500  60100.0  300500     5
Marketing  Male    59000  79000  70125.0  280500     4
Operations Female  43000  54500  49375.0  197500     4
Sales      Female  49000  71000  58000.0  290000     5
Support    Female  56000  66000  61000.0  244000     4

In [47]:
data.head(2)

   Empid          name  gender  age  salary       city Department
0  E1001  Aarav Sharma    Male   24   42000     Mumbai         HR
1  E1002    Priya Nair  Female   29   58000  Bengaluru    Finance

In [48]:
# Department + City wise salary sum nikalo.
grp = data.groupby(["Department", "city"]).agg({"salary":"sum"})

In [49]:
grp

                               salary
Department city
Admin      Ahmedabad            69000
           Mysuru               46000
           Nagpur               57500
           Noida                76000
Finance    Bengaluru            58000
           Jamshedpur           51500
           Lucknow              45000
           Ranchi               73500
           Thiruvananthapuram   68000
HR         Chandigarh           67000
           Gurugram             48000
           Kanpur               62500
           Meerut               81000
           Mumbai               42000
IT         Delhi                64000
           Jaipur               61000
           Patna                52000
           Rajkot               68500
           Surat                55000
Marketing  Agra                 70500
           Faridabad            79000
           Indore               59000
           Pune                 72000
Operations Bhopal               43000
           Kolkata              47000
           Ludhiana             54500
           Visakhapatnam        53000
Sales      Amritsar             60500
           Chennai              51000
           Dehradun             58500
           Kochi                71000
           Vadodara             49000
Support    Bhubaneswar          62000
           Coimbatore           60000
           Hyderabad            56000
           Nashik               66000

In [50]:
# Har employee ke liye department average salary column banao (transform).

data["Avg_salary"] = data.groupby(["Department"])["salary"].transform("mean")

In [52]:
data.head(5)

   Empid          name  gender  age  salary       city Department  Avg_salary
0  E1001  Aarav Sharma    Male   24   42000     Mumbai         HR     60100.0
1  E1002    Priya Nair  Female   29   58000  Bengaluru    Finance     59200.0
2  E1003   Rohan Mehta    Male   31   64000      Delhi         IT     60100.0
3  E1004    Sneha Iyer  Female   27   51000    Chennai      Sales     58000.0
4  E1005  Vikram Singh    Male   35   72000       Pune  Marketing     70125.0

In [53]:
# Jinki average salary 50000 se kam hai un departments ko hatao (filter).

data = data.groupby(["Department"]).filter(
    lambda x: x["salary"].mean() >= 50000
)

In [55]:
data.head(4)

   Empid          name  gender  age  salary       city Department  Avg_salary
0  E1001  Aarav Sharma    Male   24   42000     Mumbai         HR     60100.0
1  E1002    Priya Nair  Female   29   58000  Bengaluru    Finance     59200.0
2  E1003   Rohan Mehta    Male   31   64000      Delhi         IT     60100.0
3  E1004    Sneha Iyer  Female   27   51000    Chennai      Sales     58000.0

In [56]:
# Custom names ke saath agg() use karo.
grp = data.groupby(["Department"]).agg(
    Total_salary = ("salary", "sum"),
    avg_Salary = ("salary", "mean"),
    Max_salary = ("salary", "max")
)

In [57]:
grp

            Total_salary  avg_Salary  Max_salary
Department
Admin             248500     62125.0       76000
Finance           296000     59200.0       73500
HR                300500     60100.0       81000
IT                300500     60100.0       68500
Marketing         280500     70125.0       79000
Sales             290000     58000.0       71000
Support           244000     61000.0       66000