In [16]:
import pandas as pd

In [17]:
df1 = pd.read_excel("compney bio.xlsx")
df2 = pd.read_excel("compney salary.xlsx")

In [18]:
df1.head(3)

    name   eid  age  gender  City Department
0  Aarav  E101   24    Male   NaN         ML
1   Diya  E102   29  Female   NaN         AI
2  Rahul  E103   31    Male   NaN       DATA

In [19]:
df2.head(3)

    name   eid  salary  City Department
0  Aarav  E101   35000   NaN         ML
1   Diya  E102   38000   NaN         AI
2  Rahul  E103   42000   NaN       DATA

In [20]:
# Employee aur Salary table ko inner join karo.
pd.merge(df1,df2,how="inner")

      name   eid  age  gender  City Department  salary
0    Aarav  E101   24    Male   NaN         ML   35000
1     Diya  E102   29  Female   NaN         AI   38000
2    Rahul  E103   31    Male   NaN       DATA   42000
3    Anaya  E104   26  Female   NaN         HR   36000
4   Vikram  E105   35    Male   NaN         ML   40000
5    Sneha  E106   28  Female   NaN         ML   45000
6    Arjun  E107   30    Male   NaN         AI   39000
7    Meera  E108   27  Female   NaN         HR   47000
8    Kabir  E109   33    Male   NaN       DATA   41000
9   Ishita  E110   25  Female   NaN         ML   43000
10   Rohan  E111   32    Male   NaN         AI   37000
11   Priya  E112   29  Female   NaN       DATA   48000
12  Aditya  E113   34    Male   NaN         HR   44000
13   Kavya  E114   23  Female   NaN         ML   46000
14     Dev  E115   36    Male   NaN         ML   52000
15   Naina  E116   28  Female   NaN         AI   34000
16    Yash  E117   31    Male   NaN         HR   50000
17    Tara  E118   26  Female   NaN       DATA   53000
18   Manav  E119   37    Male   NaN         ML   40500
19    Riya  E120   24  Female   NaN         AI   49500

In [21]:
print(pd.merge(df2,df1,how="left"))

      name   eid  salary  City Department  age  gender
0    Aarav  E101   35000   NaN         ML   24    Male
1     Diya  E102   38000   NaN         AI   29  Female
2    Rahul  E103   42000   NaN       DATA   31    Male
3    Anaya  E104   36000   NaN         HR   26  Female
4   Vikram  E105   40000   NaN         ML   35    Male
5    Sneha  E106   45000   NaN         ML   28  Female
6    Arjun  E107   39000   NaN         AI   30    Male
7    Meera  E108   47000   NaN         HR   27  Female
8    Kabir  E109   41000   NaN       DATA   33    Male
9   Ishita  E110   43000   NaN         ML   25  Female
10   Rohan  E111   37000   NaN         AI   32    Male
11   Priya  E112   48000   NaN       DATA   29  Female
12  Aditya  E113   44000   NaN         HR   34    Male
13   Kavya  E114   46000   NaN         ML   23  Female
14     Dev  E115   52000   NaN         ML   36    Male
15   Naina  E116   34000   NaN         AI   28  Female
16    Yash  E117   50000   NaN         HR   31    Male
17    Tara  E118   53000   NaN       DATA   26  Female
18   Manav  E119   40500   NaN         ML   37    Male
19    Riya  E120   49500   NaN         AI   24  Female

In [22]:
# Outer join karo.
print(pd.merge(df1,df2,how="outer"))

# also shows if values are not exist

      name   eid  age  gender  City Department  salary
0    Aarav  E101   24    Male   NaN         ML   35000
1   Aditya  E113   34    Male   NaN         HR   44000
2    Anaya  E104   26  Female   NaN         HR   36000
3    Arjun  E107   30    Male   NaN         AI   39000
4      Dev  E115   36    Male   NaN         ML   52000
5     Diya  E102   29  Female   NaN         AI   38000
6   Ishita  E110   25  Female   NaN         ML   43000
7    Kabir  E109   33    Male   NaN       DATA   41000
8    Kavya  E114   23  Female   NaN         ML   46000
9    Manav  E119   37    Male   NaN         ML   40500
10   Meera  E108   27  Female   NaN         HR   47000
11   Naina  E116   28  Female   NaN         AI   34000
12   Priya  E112   29  Female   NaN       DATA   48000
13   Rahul  E103   31    Male   NaN       DATA   42000
14    Riya  E120   24  Female   NaN         AI   49500
15   Rohan  E111   32    Male   NaN         AI   37000
16   Sneha  E106   28  Female   NaN         ML   45000
17    Tara  E118   26  Female   NaN       DATA   53000
18  Vikram  E105   35    Male   NaN         ML   40000
19    Yash  E117   31    Male   NaN         HR   50000

In [23]:
# Different column names use karke merge karo.
print(pd.merge(df1,df2,on="eid"))

    name_x   eid  age  gender  City_x Department_x  name_y  salary  City_y  \
0    Aarav  E101   24    Male     NaN           ML   Aarav   35000     NaN
1     Diya  E102   29  Female     NaN           AI    Diya   38000     NaN
2    Rahul  E103   31    Male     NaN         DATA   Rahul   42000     NaN
3    Anaya  E104   26  Female     NaN           HR   Anaya   36000     NaN
4   Vikram  E105   35    Male     NaN           ML  Vikram   40000     NaN
5    Sneha  E106   28  Female     NaN           ML   Sneha   45000     NaN
6    Arjun  E107   30    Male     NaN           AI   Arjun   39000     NaN
7    Meera  E108   27  Female     NaN           HR   Meera   47000     NaN
8    Kabir  E109   33    Male     NaN         DATA   Kabir   41000     NaN
9   Ishita  E110   25  Female     NaN           ML  Ishita   43000     NaN
10   Rohan  E111   32    Male     NaN           AI   Rohan   37000     NaN
11   Priya  E112   29  Female     NaN         DATA   Priya   48000     NaN
12  Aditya  E113   34    Male     NaN           HR  Aditya   44000     NaN
13   Kavya  E114   23  Female     NaN           ML   Kavya   46000     NaN
14     Dev  E115   36    Male     NaN           ML     Dev   52000     NaN
15   Naina  E116   28  Female     NaN           AI   Naina   34000     NaN
16    Yash  E117   31    Male     NaN           HR    Yash   50000     NaN
17    Tara  E118   26  Female     NaN         DATA    Tara   53000     NaN
18   Manav  E119   37    Male     NaN           ML   Manav   40500     NaN
19    Riya  E120   24  Female     NaN           AI    Riya   49500     NaN

   Department_y
0            ML
1            AI
2          DATA
3            HR
4            ML
5            ML
6            AI
7            HR
8          DATA
9            ML
10           AI
11         DATA
12           HR
13           ML
14           ML
15           AI
16           HR
17         DATA
18           ML
19           AI

In [26]:
df1.head(5)

     name   eid  age  gender  City Department
0   Aarav  E101   24    Male   NaN         ML
1    Diya  E102   29  Female   NaN         AI
2   Rahul  E103   31    Male   NaN       DATA
3   Anaya  E104   26  Female   NaN         HR
4  Vikram  E105   35    Male   NaN         ML

In [27]:
# Department + City par merge karo.
print(pd.merge(df1,df2,on="Department"))

    name_x eid_x  age  gender  City_x Department  name_y eid_y  salary  City_y
0    Aarav  E101   24    Male     NaN         ML   Aarav  E101   35000     NaN
1    Aarav  E101   24    Male     NaN         ML  Vikram  E105   40000     NaN
2    Aarav  E101   24    Male     NaN         ML   Sneha  E106   45000     NaN
3    Aarav  E101   24    Male     NaN         ML  Ishita  E110   43000     NaN
4    Aarav  E101   24    Male     NaN         ML   Kavya  E114   46000     NaN
..     ...   ...  ...     ...     ...        ...     ...   ...     ...     ...
101   Riya  E120   24  Female     NaN         AI    Diya  E102   38000     NaN
102   Riya  E120   24  Female     NaN         AI   Arjun  E107   39000     NaN
103   Riya  E120   24  Female     NaN         AI   Rohan  E111   37000     NaN
104   Riya  E120   24  Female     NaN         AI   Naina  E116   34000     NaN
105   Riya  E120   24  Female     NaN         AI    Riya  E120   49500     NaN

[106 rows x 10 columns]

In [28]:
# indicator=True use karo.
print(pd.merge(df1,df2,on="eid", indicator=True))

    name_x   eid  age  gender  City_x Department_x  name_y  salary  City_y  \
0    Aarav  E101   24    Male     NaN           ML   Aarav   35000     NaN
1     Diya  E102   29  Female     NaN           AI    Diya   38000     NaN
2    Rahul  E103   31    Male     NaN         DATA   Rahul   42000     NaN
3    Anaya  E104   26  Female     NaN           HR   Anaya   36000     NaN
4   Vikram  E105   35    Male     NaN           ML  Vikram   40000     NaN
5    Sneha  E106   28  Female     NaN           ML   Sneha   45000     NaN
6    Arjun  E107   30    Male     NaN           AI   Arjun   39000     NaN
7    Meera  E108   27  Female     NaN           HR   Meera   47000     NaN
8    Kabir  E109   33    Male     NaN         DATA   Kabir   41000     NaN
9   Ishita  E110   25  Female     NaN           ML  Ishita   43000     NaN
10   Rohan  E111   32    Male     NaN           AI   Rohan   37000     NaN
11   Priya  E112   29  Female     NaN         DATA   Priya   48000     NaN
12  Aditya  E113   34    Male     NaN           HR  Aditya   44000     NaN
13   Kavya  E114   23  Female     NaN           ML   Kavya   46000     NaN
14     Dev  E115   36    Male     NaN           ML     Dev   52000     NaN
15   Naina  E116   28  Female     NaN           AI   Naina   34000     NaN
16    Yash  E117   31    Male     NaN           HR    Yash   50000     NaN
17    Tara  E118   26  Female     NaN         DATA    Tara   53000     NaN
18   Manav  E119   37    Male     NaN           ML   Manav   40500     NaN
19    Riya  E120   24  Female     NaN           AI    Riya   49500     NaN

   Department_y _merge
0            ML   both
1            AI   both
2          DATA   both
3            HR   both
4            ML   both
5            ML   both
6            AI   both
7            HR   both
8          DATA   both
9            ML   both
10           AI   both
11         DATA   both
12           HR   both
13           ML   both
14           ML   both
15           AI   both
16           HR   both
17         DATA   both
18           ML   both
19           AI   both