In [1]:
print("Hello")

Hello

In [2]:
import numpy as np
import pandas as pd

In [3]:
data1 = {"EmpId":["E01","E02","E03","E04","E05","E06"],
         "Name":["Anshul","Ram","Shyam","Raju","Koi","Rajesh"],
         "Age":[33,25,45,21,25,27]}

data2 = {"EmpId":["E01","E02","E03","E04","E05","E06"],
         "Salary":[45000,56000,70000,19000,24000,29000]}

df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data2)

In [4]:
df1

  EmpId    Name  Age
0   E01  Anshul   33
1   E02     Ram   25
2   E03   Shyam   45
3   E04    Raju   21
4   E05     Koi   25
5   E06  Rajesh   27

In [5]:
df2

  EmpId  Salary
0   E01   45000
1   E02   56000
2   E03   70000
3   E04   19000
4   E05   24000
5   E06   29000

In [6]:
pd.merge(left=df1, right=df2, on="EmpId")

  EmpId    Name  Age  Salary
0   E01  Anshul   33   45000
1   E02     Ram   25   56000
2   E03   Shyam   45   70000
3   E04    Raju   21   19000
4   E05     Koi   25   24000
5   E06  Rajesh   27   29000

In [7]:
data1 = {"EmpId":["E01","E02","E03","E04","E05","E06"],
         "Name":["Anshul","Ram","Shyam","Raju","Koi","Rajesh"],
         "Age":[33,25,45,21,25,27]}

data2 = {"EmpId":["E01","E07","E03","E04","E05","E08"],
         "Salary":[45000,56000,70000,19000,24000,29000]}

df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data2)

In [8]:
df1

  EmpId    Name  Age
0   E01  Anshul   33
1   E02     Ram   25
2   E03   Shyam   45
3   E04    Raju   21
4   E05     Koi   25
5   E06  Rajesh   27

In [9]:
df2

  EmpId  Salary
0   E01   45000
1   E07   56000
2   E03   70000
3   E04   19000
4   E05   24000
5   E08   29000

In [10]:
pd.merge(df1,df2,on="EmpId", how="left")

  EmpId    Name  Age   Salary
0   E01  Anshul   33  45000.0
1   E02     Ram   25      NaN
2   E03   Shyam   45  70000.0
3   E04    Raju   21  19000.0
4   E05     Koi   25  24000.0
5   E06  Rajesh   27      NaN

In [11]:
pd.merge(df1,df2,on="EmpId", how="right")

  EmpId    Name   Age  Salary
0   E01  Anshul  33.0   45000
1   E07     NaN   NaN   56000
2   E03   Shyam  45.0   70000
3   E04    Raju  21.0   19000
4   E05     Koi  25.0   24000
5   E08     NaN   NaN   29000

In [13]:
pd.merge(df1,df2,on="EmpId",how="outer")

  EmpId    Name   Age   Salary
0   E01  Anshul  33.0  45000.0
1   E02     Ram  25.0      NaN
2   E03   Shyam  45.0  70000.0
3   E04    Raju  21.0  19000.0
4   E05     Koi  25.0  24000.0
5   E06  Rajesh  27.0      NaN
6   E07     NaN   NaN  56000.0
7   E08     NaN   NaN  29000.0

In [17]:
data1 = {"EmpId":["E01","E02","E03","E04","E05","E06"],
         "Name":["Anshul","Ram","Shyam","Raju","Koi","Rajesh"],
         "Age":[33,25,45,21,25,27]}

data2 = {"EmployId":["E01","E07","E03","E04","E05","E08"],
         "Salary":[45000,56000,70000,19000,24000,29000]}

In [18]:
df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data2)

In [19]:
pd.merge(df1, df2, left_on="EmpId", right_on="EmployId")

  EmpId    Name  Age EmployId  Salary
0   E01  Anshul   33      E01   45000
1   E03   Shyam   45      E03   70000
2   E04    Raju   21      E04   19000
3   E05     Koi   25      E05   24000

In [20]:
pd.merge(df1, df2, left_on="EmpId", right_on="EmployId",indicator=True)

  EmpId    Name  Age EmployId  Salary _merge
0   E01  Anshul   33      E01   45000   both
1   E03   Shyam   45      E03   70000   both
2   E04    Raju   21      E04   19000   both
3   E05     Koi   25      E05   24000   both

Concatenate

In [24]:
data1 = {"EmpId":["E01","E02","E03","E04","E05","E06"],
         "Name":["Anshul","Ram","Shyam","Raju","Koi","Rajesh"],
         "Age":[33,25,45,21,25,27]}

data2 = {"EmpId":["E07","E08","E09","E10","E011","E012"],
         "Name":["Bittu","Kittu","Chittu","Ritu","ramshyam","Ghanshyam"],
         "Age":[45,56,27,19,24,29]}

df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data2)

In [25]:
print(pd.concat([df1,df2]))

  EmpId       Name  Age
0   E01     Anshul   33
1   E02        Ram   25
2   E03      Shyam   45
3   E04       Raju   21
4   E05        Koi   25
5   E06     Rajesh   27
0   E07      Bittu   45
1   E08      Kittu   56
2   E09     Chittu   27
3   E10       Ritu   19
4  E011   ramshyam   24
5  E012  Ghanshyam   29

In [27]:
# df1.join(df2)

# works when columns are different