In [1]:
import pandas as pd

In [2]:
d = {"idx":[1,2,3,4,5],
     "Name":["Anshul","Raj","Ram","Shyam","Koi"],
     "Age":[22,24,19,42,33]}

data = pd.DataFrame(d)
data

   idx    Name  Age
0    1  Anshul   22
1    2     Raj   24
2    3     Ram   19
3    4   Shyam   42
4    5     Koi   33

In [3]:
print(data.pivot(index="idx", columns="Name", values="Age"))

Name  Anshul   Koi   Raj   Ram  Shyam
idx
1       22.0   NaN   NaN   NaN    NaN
2        NaN   NaN  24.0   NaN    NaN
3        NaN   NaN   NaN  19.0    NaN
4        NaN   NaN   NaN   NaN   42.0
5        NaN  33.0   NaN   NaN    NaN

In [4]:
data["city"] = ["jaipur","Delhi","Jaipur","Gujrat","Delhi"]

In [5]:
data

   idx    Name  Age    city
0    1  Anshul   22  jaipur
1    2     Raj   24   Delhi
2    3     Ram   19  Jaipur
3    4   Shyam   42  Gujrat
4    5     Koi   33   Delhi

In [6]:
print(data.pivot(index="idx", columns="Name", values=["Age","city"]))

        Age                         city
Name Anshul  Koi  Raj  Ram Shyam  Anshul    Koi    Raj     Ram   Shyam
idx
1        22  NaN  NaN  NaN   NaN  jaipur    NaN    NaN     NaN     NaN
2       NaN  NaN   24  NaN   NaN     NaN    NaN  Delhi     NaN     NaN
3       NaN  NaN  NaN   19   NaN     NaN    NaN    NaN  Jaipur     NaN
4       NaN  NaN  NaN  NaN    42     NaN    NaN    NaN     NaN  Gujrat
5       NaN   33  NaN  NaN   NaN     NaN  Delhi    NaN     NaN     NaN

Melting

In [7]:
data = {"Name":["Anshul","Raj","Priya","Shyam","Koi"],
        "Gender":["M","M","F","M","F"],
        "Age":[22,24,19,42,33]}

df = pd.DataFrame(data)

In [8]:
df

     Name Gender  Age
0  Anshul      M   22
1     Raj      M   24
2   Priya      F   19
3   Shyam      M   42
4     Koi      F   33

In [9]:
print(pd.melt(df, id_vars=["Name"], value_vars=["Gender"]))

     Name variable value
0  Anshul   Gender     M
1     Raj   Gender     M
2   Priya   Gender     F
3   Shyam   Gender     M
4     Koi   Gender     F

In [10]:
print(pd.melt(df, id_vars=["Name"], value_vars=["Gender", "Age"]))

     Name variable value
0  Anshul   Gender     M
1     Raj   Gender     M
2   Priya   Gender     F
3   Shyam   Gender     M
4     Koi   Gender     F
5  Anshul      Age    22
6     Raj      Age    24
7   Priya      Age    19
8   Shyam      Age    42
9     Koi      Age    33

In [12]:
print(pd.melt(df, id_vars=["Name"], value_vars=["Gender"], var_name="Var_gender"))

     Name Var_gender value
0  Anshul     Gender     M
1     Raj     Gender     M
2   Priya     Gender     F
3   Shyam     Gender     M
4     Koi     Gender     F