In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_excel("add row practice.xlsx")
data.head(5)

     EMPID          Name  Age  Salary  Gender Joining Date
0  EMP1001  Aarav Sharma   28   52000    Male   2021-03-15
1  EMP1002    Diya Patel   31   61000  Female   2019-07-22
2  EMP1003   Rohan Mehta   26   48000    Male   2022-01-10
3  EMP1004    Sneha Iyer   35   75000  Female   2018-11-05
4  EMP1005   Karan Verma   29   56000    Male   2020-06-18

In [3]:
# Salary ka 20% Bonus column banao.
data["Bonas"] = (data["Salary"]/100)*25

In [5]:
data.head(5)

     EMPID          Name  Age  Salary  Gender Joining Date    Bonas
0  EMP1001  Aarav Sharma   28   52000    Male   2021-03-15  13000.0
1  EMP1002    Diya Patel   31   61000  Female   2019-07-22  15250.0
2  EMP1003   Rohan Mehta   26   48000    Male   2022-01-10  12000.0
3  EMP1004    Sneha Iyer   35   75000  Female   2018-11-05  18750.0
4  EMP1005   Karan Verma   29   56000    Male   2020-06-18  14000.0

In [6]:
# Salary + Bonus = Total Salary column banao.
data["Total Salary"] = data["Salary"] + data["Bonas"]

In [7]:
data.head(4)

,EMPID,Name,Age,Salary,Gender,Joining Date,Bonas,Total Salary
0,EMP1001,Aarav Sharma,28,52000,Male,2021-03-15,13000.0,65000.0
1,EMP1002,Diya Patel,31,61000,Female,2019-07-22,15250.0,76250.0
2,EMP1003,Rohan Mehta,26,48000,Male,2022-01-10,12000.0,60000.0
3,EMP1004,Sneha Iyer,35,75000,Female,2018-11-05,18750.0,93750.0

In [9]:
# Name se email column banao.
data["Email"] = data["Name"].str.lower() + "@gmail.com"

In [10]:
data.head(5)

,EMPID,Name,Age,Salary,Gender,Joining Date,Bonas,Total Salary,Email
0,EMP1001,Aarav Sharma,28,52000,Male,2021-03-15,13000.0,65000.0,aarav sharma@gmail.com
1,EMP1002,Diya Patel,31,61000,Female,2019-07-22,15250.0,76250.0,diya patel@gmail.com
2,EMP1003,Rohan Mehta,26,48000,Male,2022-01-10,12000.0,60000.0,rohan mehta@gmail.com
3,EMP1004,Sneha Iyer,35,75000,Female,2018-11-05,18750.0,93750.0,sneha iyer@gmail.com
4,EMP1005,Karan Verma,29,56000,Male,2020-06-18,14000.0,70000.0,karan verma@gmail.com

In [11]:
# Age > 30 ho to "Senior" warna "Junior".
data["Post"] = np.where(
    data["Age"] > 30,
    "Senior",
    "Jonior"
)

In [13]:
data.head(5)

,EMPID,Name,Age,Salary,Gender,Joining Date,Bonas,Total Salary,Email,Post
0,EMP1001,Aarav Sharma,28,52000,Male,2021-03-15,13000.0,65000.0,aarav sharma@gmail.com,Jonior
1,EMP1002,Diya Patel,31,61000,Female,2019-07-22,15250.0,76250.0,diya patel@gmail.com,Senior
2,EMP1003,Rohan Mehta,26,48000,Male,2022-01-10,12000.0,60000.0,rohan mehta@gmail.com,Jonior
3,EMP1004,Sneha Iyer,35,75000,Female,2018-11-05,18750.0,93750.0,sneha iyer@gmail.com,Senior
4,EMP1005,Karan Verma,29,56000,Male,2020-06-18,14000.0,70000.0,karan verma@gmail.com,Jonior

In [14]:
# Salary ko lakh me convert karo.
data["Salary in Lacs"] = data["Total Salary"]/100000

In [15]:
data.head(5)

,EMPID,Name,Age,Salary,Gender,Joining Date,Bonas,Total Salary,Email,Post,Salary in Lacs
0,EMP1001,Aarav Sharma,28,52000,Male,2021-03-15,13000.0,65000.0,aarav sharma@gmail.com,Jonior,0.6500
1,EMP1002,Diya Patel,31,61000,Female,2019-07-22,15250.0,76250.0,diya patel@gmail.com,Senior,0.7625
2,EMP1003,Rohan Mehta,26,48000,Male,2022-01-10,12000.0,60000.0,rohan mehta@gmail.com,Jonior,0.6000
3,EMP1004,Sneha Iyer,35,75000,Female,2018-11-05,18750.0,93750.0,sneha iyer@gmail.com,Senior,0.9375
4,EMP1005,Karan Verma,29,56000,Male,2020-06-18,14000.0,70000.0,karan verma@gmail.com,Jonior,0.7000

In [16]:
# Joining_Date se Year aur Month nikalo.
data["Joinong_year"] = data["Joining Date"].dt.year

In [18]:
data.head(3)

,EMPID,Name,Age,Salary,Gender,Joining Date,Bonas,Total Salary,Email,Post,Salary in Lacs,Joinong_year
0,EMP1001,Aarav Sharma,28,52000,Male,2021-03-15,13000.0,65000.0,aarav sharma@gmail.com,Jonior,0.6500,2021
1,EMP1002,Diya Patel,31,61000,Female,2019-07-22,15250.0,76250.0,diya patel@gmail.com,Senior,0.7625,2019
2,EMP1003,Rohan Mehta,26,48000,Male,2022-01-10,12000.0,60000.0,rohan mehta@gmail.com,Jonior,0.6000,2022

In [19]:
data["Joining_Month"] = data["Joining Date"].dt.month

In [20]:
data.head(4)

,EMPID,Name,Age,Salary,Gender,Joining Date,Bonas,Total Salary,Email,Post,Salary in Lacs,Joinong_year,Joining_Month
0,EMP1001,Aarav Sharma,28,52000,Male,2021-03-15,13000.0,65000.0,aarav sharma@gmail.com,Jonior,0.6500,2021,3
1,EMP1002,Diya Patel,31,61000,Female,2019-07-22,15250.0,76250.0,diya patel@gmail.com,Senior,0.7625,2019,7
2,EMP1003,Rohan Mehta,26,48000,Male,2022-01-10,12000.0,60000.0,rohan mehta@gmail.com,Jonior,0.6000,2022,1
3,EMP1004,Sneha Iyer,35,75000,Female,2018-11-05,18750.0,93750.0,sneha iyer@gmail.com,Senior,0.9375,2018,11

In [21]:
data["Joining_Month name"] = data["Joining Date"].dt.month_name()

In [22]:
data.head(3)

,EMPID,Name,Age,Salary,Gender,Joining Date,Bonas,Total Salary,Email,Post,Salary in Lacs,Joinong_year,Joining_Month,Joining_Month name
0,EMP1001,Aarav Sharma,28,52000,Male,2021-03-15,13000.0,65000.0,aarav sharma@gmail.com,Jonior,0.6500,2021,3,March
1,EMP1002,Diya Patel,31,61000,Female,2019-07-22,15250.0,76250.0,diya patel@gmail.com,Senior,0.7625,2019,7,July
2,EMP1003,Rohan Mehta,26,48000,Male,2022-01-10,12000.0,60000.0,rohan mehta@gmail.com,Jonior,0.6000,2022,1,January

In [25]:
# Salary ranking column banao.
data["ranking"] = data["Salary"].rank(ascending=False)

In [26]:
data.head(4)

,EMPID,Name,Age,Salary,Gender,Joining Date,Bonas,Total Salary,Email,Post,Salary in Lacs,Joinong_year,Joining_Month,Joining_Month name,ranking
0,EMP1001,Aarav Sharma,28,52000,Male,2021-03-15,13000.0,65000.0,aarav sharma@gmail.com,Jonior,0.6500,2021,3,March,33.0
1,EMP1002,Diya Patel,31,61000,Female,2019-07-22,15250.0,76250.0,diya patel@gmail.com,Senior,0.7625,2019,7,July,20.0
2,EMP1003,Rohan Mehta,26,48000,Male,2022-01-10,12000.0,60000.0,rohan mehta@gmail.com,Jonior,0.6000,2022,1,January,37.0
3,EMP1004,Sneha Iyer,35,75000,Female,2018-11-05,18750.0,93750.0,sneha iyer@gmail.com,Senior,0.9375,2018,11,November,6.0

In [30]:
# Running total of salary nikalo.
data["Running Salary"] = data["Salary"].cumsum()

In [31]:
data.head(4)

,EMPID,Name,Age,Salary,Gender,Joining Date,Bonas,Total Salary,Email,Post,Salary in Lacs,Joinong_year,Joining_Month,Joining_Month name,ranking,Running Salary
0,EMP1001,Aarav Sharma,28,52000,Male,2021-03-15,13000.0,65000.0,aarav sharma@gmail.com,Jonior,0.6500,2021,3,March,33.0,52000
1,EMP1002,Diya Patel,31,61000,Female,2019-07-22,15250.0,76250.0,diya patel@gmail.com,Senior,0.7625,2019,7,July,20.0,113000
2,EMP1003,Rohan Mehta,26,48000,Male,2022-01-10,12000.0,60000.0,rohan mehta@gmail.com,Jonior,0.6000,2022,1,January,37.0,161000
3,EMP1004,Sneha Iyer,35,75000,Female,2018-11-05,18750.0,93750.0,sneha iyer@gmail.com,Senior,0.9375,2018,11,November,6.0,236000

In [32]:
# Salary ka percentage contribution nikalo.
t = data["Salary"].sum()
data["Contribution"] = (data["Salary"]/t)*100

In [33]:
data.head(5)

,EMPID,Name,Age,Salary,Gender,Joining Date,Bonas,Total Salary,Email,Post,Salary in Lacs,Joinong_year,Joining_Month,Joining_Month name,ranking,Running Salary,Contribution
0,EMP1001,Aarav Sharma,28,52000,Male,2021-03-15,13000.0,65000.0,aarav sharma@gmail.com,Jonior,0.6500,2021,3,March,33.0,52000,2.091293
1,EMP1002,Diya Patel,31,61000,Female,2019-07-22,15250.0,76250.0,diya patel@gmail.com,Senior,0.7625,2019,7,July,20.0,113000,2.453248
2,EMP1003,Rohan Mehta,26,48000,Male,2022-01-10,12000.0,60000.0,rohan mehta@gmail.com,Jonior,0.6000,2022,1,January,37.0,161000,1.930424
3,EMP1004,Sneha Iyer,35,75000,Female,2018-11-05,18750.0,93750.0,sneha iyer@gmail.com,Senior,0.9375,2018,11,November,6.0,236000,3.016288
4,EMP1005,Karan Verma,29,56000,Male,2020-06-18,14000.0,70000.0,karan verma@gmail.com,Jonior,0.7000,2020,6,June,27.5,292000,2.252162

In [ ]:
# Name ke first 3 letters wala column banao.
data["sort Name"] = data["Name"].str[0:3]

# data["sort Name"] = data["Name"].str.slice(0,3)

In [35]:
data.head(4)

,EMPID,Name,Age,Salary,Gender,Joining Date,Bonas,Total Salary,Email,Post,Salary in Lacs,Joinong_year,Joining_Month,Joining_Month name,ranking,Running Salary,Contribution,sort Name
0,EMP1001,Aarav Sharma,28,52000,Male,2021-03-15,13000.0,65000.0,aarav sharma@gmail.com,Jonior,0.6500,2021,3,March,33.0,52000,2.091293,Aar
1,EMP1002,Diya Patel,31,61000,Female,2019-07-22,15250.0,76250.0,diya patel@gmail.com,Senior,0.7625,2019,7,July,20.0,113000,2.453248,Diy
2,EMP1003,Rohan Mehta,26,48000,Male,2022-01-10,12000.0,60000.0,rohan mehta@gmail.com,Jonior,0.6000,2022,1,January,37.0,161000,1.930424,Roh
3,EMP1004,Sneha Iyer,35,75000,Female,2018-11-05,18750.0,93750.0,sneha iyer@gmail.com,Senior,0.9375,2018,11,November,6.0,236000,3.016288,Sne